# auth_config.example.yaml
# -------------------------
# Copie en auth_config.yaml et adapte, OU lance : python setup_auth.py
# NE JAMAIS committer auth_config.yaml dans Git !

credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrateur
      password: BCRYPT_HASH_ICI
      role: admin
      failed_login_attempts: 0
      logged_in: false
    utilisateur1:
      email: user1@example.com
      name: Prenom Nom
      password: BCRYPT_HASH_ICI_2
      role: user
      failed_login_attempts: 0
      logged_in: false

cookie:
  expiry_days: 7
  key: remplace_par_une_cle_secrete_aleatoire_de_64_chars
  name: sirene_dashboard_auth

pre-authorized:
  emails:
    - admin@example.com
    - user1@example.com
